version: "3.9"

services:
  redis:
    image: redis
    restart: always

  project:
    restart: always
    build:
      context: ./website
    ports:
      - "8000:8000"

  worker:
    restart: always
    build:
      context: ./website
    env_file:
      - ./website/.env
    command: ['celery', '--workdir=/app/website', '-A', 'config', 'worker']
